# ============================================================================
# PLANTILLAS ESOTÉRICAS PARA GENERACIÓN DE ANUNCIOS
# Sistema de templates predefinidos para nichos esotéricos
# Versión: 2.0
# Fecha: 2025-01-13
# ============================================================================

version: "2.0"
last_updated: "2025-01-13"

# ============================================================================
# CONFIGURACIÓN GLOBAL
# ============================================================================
global_settings:
  max_keywords_per_template: 30
  default_num_headlines: 15
  default_num_descriptions: 4
  default_tone: "emocional"
  auto_validate: true
  enable_dynamic_keywords: true

# ============================================================================
# PLANTILLAS POR CATEGORÍA
# ============================================================================
templates:
  
  # --------------------------------------------------------------------------
  # BRUJERÍA DE PAREJA
  # --------------------------------------------------------------------------
  brujeria_pareja:
    name: "Brujería de Pareja"
    description: "Hechizos y rituales para amor, reconciliación y unión de parejas"
    icon: "💑"
    color: "#FF1744"
    
    keywords_sugeridas:
      primarias:
        - "amarres de amor"
        - "hechizos de pareja"
        - "brujería para el amor"
        - "ritual de unión"
        - "magia para reconciliación"
        - "amarres efectivos"
        - "hechizos poderosos"
        - "brujería blanca amor"
        - "ritual para recuperar pareja"
        - "magia roja amor"
      
      secundarias:
        - "endulzamiento de pareja"
        - "ritual de atracción"
        - "magia para enamorar"
        - "hechizo de amor eterno"
        - "brujería para matrimonio"
        - "amarres caseros"
        - "ritual luna llena amor"
        - "magia para conquistar"
        - "hechizo de fidelidad"
        - "brujería para dominar"
      
      long_tail:
        - "amarres de amor que funcionan rápido"
        - "hechizos para recuperar a tu ex"
        - "brujería efectiva para el amor verdadero"
        - "ritual poderoso para unir parejas"
        - "magia blanca para reconciliación"
        - "amarres de amor con foto y nombre"
        - "hechizos de amor con velas rojas"
        - "brujería para atraer al ser amado"
        - "ritual de amor con miel"
        - "magia para que regrese tu pareja"
    
    tonos_recomendados:
      - "emocional"
      - "urgente"
      - "esperanzador"
      - "místico"
      - "profesional"
    
    ctas_sugeridos:
      - "Recupera a Tu Pareja Ya"
      - "Hechizo Efectivo Garantizado"
      - "Consulta Gratis Ahora"
      - "Resultados en 24 Horas"
      - "Bruja Experta Disponible"
      - "Ritual Personalizado"
      - "Amarre Poderoso Hoy"
      - "Solución Inmediata"
      - "Magia Blanca Certificada"
      - "Pide Tu Ritual Ahora"
    
    descripciones_base:
      - "Amarres de amor efectivos y discretos. Resultados garantizados en 24-48 horas. Bruja profesional con años de experiencia."
      - "Recupera a tu pareja con magia blanca poderosa. Rituales personalizados según tu caso. Consulta inicial gratuita."
      - "Hechizos de amor que funcionan. Discretos, seguros y efectivos. No importa la distancia o el tiempo separados."
      - "Magia para unir parejas con garantía. Trabajos personalizados con foto y nombre. Resultados visibles rápidamente."
    
    url_patterns:
      - "/amarres-de-amor"
      - "/hechizos-de-pareja"
      - "/brujeria-amor"
      - "/rituales-reconciliacion"
      - "/magia-para-parejas"
    
    targeting_suggestions:
      age_range: "25-54"
      gender: "all"
      locations:
        - "México"
        - "España"
        - "Colombia"
        - "Argentina"
        - "Estados Unidos (Hispanic)"
      interests:
        - "Esoterismo"
        - "Espiritualidad"
        - "Tarot"
        - "Astrología"
        - "Relaciones de pareja"
  
  # --------------------------------------------------------------------------
  # HECHIZOS GENERALES
  # --------------------------------------------------------------------------
  hechizos:
    name: "Hechizos Generales"
    description: "Hechizos para diversas necesidades: dinero, salud, protección"
    icon: "🔮"
    color: "#9C27B0"
    
    keywords_sugeridas:
      primarias:
        - "hechizos poderosos"
        - "magia efectiva"
        - "rituales mágicos"
        - "hechizos que funcionan"
        - "brujería profesional"
        - "magia blanca"
        - "hechizos rápidos"
        - "rituales efectivos"
        - "magia real"
        - "hechizos garantizados"
      
      secundarias:
        - "hechizos de dinero"
        - "hechizos de protección"
        - "hechizos de salud"
        - "hechizos de suerte"
        - "hechizos de trabajo"
        - "magia para negocios"
        - "rituales de abundancia"
        - "hechizos caseros"
        - "magia antigua"
        - "brujería tradicional"
      
      long_tail:
        - "hechizos poderosos que funcionan en 24 horas"
        - "magia blanca efectiva para el dinero"
        - "rituales de protección contra enemigos"
        - "hechizos de suerte para ganar dinero"
        - "brujería profesional con garantía"
        - "magia real para cambiar tu vida"
        - "hechizos personalizados según tu caso"
        - "rituales efectivos de abundancia"
        - "magia para atraer prosperidad"
        - "hechizos de protección familiar"
    
    tonos_recomendados:
      - "místico"
      - "profesional"
      - "urgente"
      - "informativo"
      - "emocional"
    
    ctas_sugeridos:
      - "Solicita Tu Hechizo Ya"
      - "Magia Garantizada"
      - "Consulta Gratis Ahora"
      - "Ritual Personalizado"
      - "Bruja Experta Disponible"
      - "Resultados Rápidos"
      - "Hechizo Efectivo Hoy"
      - "Cambia Tu Vida Ahora"
      - "Magia Real Certificada"
      - "Pide Tu Ritual"
    
    descripciones_base:
      - "Hechizos poderosos para todas tus necesidades. Magia blanca efectiva con resultados garantizados. Bruja profesional."
      - "Rituales mágicos personalizados. Resultados visibles en poco tiempo. Consulta inicial sin costo."
      - "Magia real que funciona. Hechizos para dinero, amor, salud y protección. Discreto y seguro."
      - "Brujería profesional con años de experiencia. Trabajos efectivos garantizados. Atención personalizada."
    
    url_patterns:
      - "/hechizos"
      - "/magia-blanca"
      - "/rituales"
      - "/brujeria"
      - "/servicios-magicos"
    
    targeting_suggestions:
      age_range: "25-65"
      gender: "all"
      locations:
        - "México"
        - "España"
        - "Colombia"
        - "Argentina"
        - "Chile"
        - "Perú"
      interests:
        - "Esoterismo"
        - "Magia"
        - "Espiritualidad"
        - "Desarrollo personal"

  # --------------------------------------------------------------------------
  # CONJUROS
  # --------------------------------------------------------------------------
  conjuros:
    name: "Conjuros"
    description: "Conjuros específicos para situaciones particulares"
    icon: "✨"
    color: "#FF6F00"
    
    keywords_sugeridas:
      primarias:
        - "conjuros poderosos"
        - "conjuros efectivos"
        - "magia de conjuros"
        - "conjuros ancestrales"
        - "conjuros rápidos"
        - "conjuros garantizados"
        - "conjuros profesionales"
        - "conjuros reales"
        - "conjuros antiguos"
        - "conjuros certificados"
      
      secundarias:
        - "conjuros de amor"
        - "conjuros de dinero"
        - "conjuros de protección"
        - "conjuros de dominio"
        - "conjuros de suerte"
        - "conjuros para negocios"
        - "conjuros de salud"
        - "conjuros de venganza"
        - "conjuros de limpieza"
        - "conjuros de abundancia"
      
      long_tail:
        - "conjuros poderosos para atraer dinero rápido"
        - "conjuros efectivos de amor verdadero"
        - "magia de conjuros ancestrales garantizada"
        - "conjuros rápidos que funcionan en 24h"
        - "conjuros profesionales con resultados"
        - "conjuros reales para protección total"
        - "conjuros antiguos de poder máximo"
        - "conjuros de dominio para controlar"
        - "conjuros de suerte para ganar siempre"
        - "conjuros para atraer prosperidad inmediata"
    
    tonos_recomendados:
      - "místico"
      - "poderoso"
      - "ancestral"
      - "urgente"
      - "profesional"
    
    ctas_sugeridos:
      - "Solicita Tu Conjuro Ya"
      - "Poder Ancestral Garantizado"
      - "Conjuro Personalizado Ahora"
      - "Resultados en Horas"
      - "Magia Antigua Certificada"
      - "Consulta Gratis Hoy"
      - "Conjuro Efectivo Inmediato"
      - "Poder Real Disponible"
      - "Ritual Ancestral Ya"
      - "Cambia Tu Destino Ahora"
    
    descripciones_base:
      - "Conjuros ancestrales de gran poder. Resultados garantizados y rápidos. Magia profesional certificada."
      - "Rituales de conjuros personalizados. Poder real para cambiar tu vida. Consulta inicial gratuita."
      - "Magia antigua que funciona. Conjuros efectivos para toda necesidad. Discreto y profesional."
      - "Conjuros poderosos con garantía. Bruja experta en magia ancestral. Resultados visibles rápido."
    
    url_patterns:
      - "/conjuros"
      - "/magia-conjuros"
      - "/rituales-conjuros"
      - "/conjuros-ancestrales"
      - "/poder-magico"

  # --------------------------------------------------------------------------
  # LIMPIEZA ESPIRITUAL
  # --------------------------------------------------------------------------
  limpieza_espiritual:
    name: "Limpieza Espiritual"
    description: "Limpiezas energéticas, despojos y protección espiritual"
    icon: "🕯️"
    color: "#00BCD4"
    
    keywords_sugeridas:
      primarias:
        - "limpieza espiritual"
        - "despojo energético"
        - "limpia de energías"
        - "protección espiritual"
        - "limpieza profunda"
        - "quitar mal de ojo"
        - "limpiar aura"
        - "despojo completo"
        - "limpieza con huevo"
        - "baño de florecimiento"
      
      secundarias:
        - "limpieza de casa"
        - "limpieza de negocios"
        - "cortar ataduras"
        - "romper hechizos"
        - "eliminar energías negativas"
        - "limpieza de chakras"
        - "despojo a distancia"
        - "protección contra envidias"
        - "limpia con sahumerio"
        - "baño de sal"
      
      long_tail:
        - "limpieza espiritual profunda y efectiva"
        - "despojo energético para quitar maldiciones"
        - "limpia de energías negativas garantizada"
        - "protección espiritual contra enemigos"
        - "quitar mal de ojo con huevo"
        - "limpiar aura y chakras bloqueados"
        - "despojo completo a distancia efectivo"
        - "limpieza de casa contra energías"
        - "baño de florecimiento para atraer suerte"
        - "protección espiritual familiar total"
    
    tonos_recomendados:
      - "tranquilizador"
      - "profesional"
      - "espiritual"
      - "protector"
      - "sanador"
    
    ctas_sugeridos:
      - "Limpia Tu Energía Ya"
      - "Despojo Efectivo Ahora"
      - "Protección Garantizada"
      - "Consulta Gratis Hoy"
      - "Limpieza Profunda Ya"
      - "Elimina Energías Negativas"
      - "Siente la Diferencia"
      - "Renueva Tu Energía"
      - "Protege Tu Hogar Ahora"
      - "Despojo Profesional"
    
    descripciones_base:
      - "Limpiezas espirituales profundas y efectivas. Elimina energías negativas y protege tu vida. Profesional certificada."
      - "Despojos energéticos completos. Quita mal de ojo, envidias y maldiciones. Resultados inmediatos garantizados."
      - "Protección espiritual para ti y tu familia. Limpia tu aura y renueva tu energía. Consulta gratis."
      - "Limpieza de casa y negocios. Elimina energías estancadas. Baños de florecimiento y protección."
    
    url_patterns:
      - "/limpieza-espiritual"
      - "/despojo-energetico"
      - "/proteccion-espiritual"
      - "/limpia-energias"
      - "/baños-florecimientos"

  # --------------------------------------------------------------------------
  # AMARRES
  # --------------------------------------------------------------------------
  amarres:
    name: "Amarres"
    description: "Amarres de amor, dominio y unión permanente"
    icon: "🔗"
    color: "#E91E63"
    
    keywords_sugeridas:
      primarias:
        - "amarres de amor"
        - "amarres efectivos"
        - "amarres poderosos"
        - "amarres garantizados"
        - "amarres rápidos"
        - "amarres eternos"
        - "amarres profesionales"
        - "amarres con magia"
        - "amarres de dominio"
        - "amarres permanentes"
      
      secundarias:
        - "amarres con foto"
        - "amarres a distancia"
        - "amarres con velas"
        - "amarres de luna llena"
        - "amarres con miel"
        - "amarres de sangre"
        - "amarres caseros"
        - "amarres para matrimonio"
        - "amarres de sometimiento"
        - "amarres de obsesión"
      
      long_tail:
        - "amarres de amor que funcionan en 24 horas"
        - "amarres efectivos con foto y nombre"
        - "amarres poderosos para recuperar pareja"
        - "amarres garantizados de amor eterno"
        - "amarres rápidos y discretos profesionales"
        - "amarres eternos de unión permanente"
        - "amarres de dominio para controlar pareja"
        - "amarres con magia blanca efectiva"
        - "amarres a distancia que funcionan"
        - "amarres de luna llena poderosos"
    
    tonos_recomendados:
      - "urgente"
      - "poderoso"
      - "emocional"
      - "discreto"
      - "garantizado"
    
    ctas_sugeridos:
      - "Amarre Efectivo Ya"
      - "Recupera a Tu Pareja Hoy"
      - "Amarre Garantizado 24h"
      - "Consulta Gratis Ahora"
      - "Amarre Poderoso Inmediato"
      - "Resultados Permanentes"
      - "Bruja Experta Disponible"
      - "Amarre Discreto y Seguro"
      - "Unión Eterna Garantizada"
      - "Solicita Tu Amarre Ya"
    
    descripciones_base:
      - "Amarres de amor efectivos y permanentes. Resultados garantizados en 24-48 horas. Discretos y profesionales."
      - "Amarres poderosos con magia blanca. Recupera a tu pareja para siempre. Bruja experta certificada."
      - "Amarres eternos de unión permanente. Trabajos con foto y nombre. Consulta inicial gratuita."
      - "Amarres de dominio y control. Efectivos a distancia. Resultados visibles rápidamente."
    
    url_patterns:
      - "/amarres"
      - "/amarres-de-amor"
      - "/amarres-efectivos"
      - "/amarres-poderosos"
      - "/rituales-de-union"

  # --------------------------------------------------------------------------
  # TAROT Y LECTURA
  # --------------------------------------------------------------------------
  tarot:
    name: "Tarot y Lectura"
    description: "Lecturas de tarot, videncia y consultas esotéricas"
    icon: "🃏"
    color: "#673AB7"
    
    keywords_sugeridas:
      primarias:
        - "lectura de tarot"
        - "tarot en línea"
        - "tarot profesional"
        - "consulta de tarot"
        - "tarot certero"
        - "videncia online"
        - "lectura de cartas"
        - "tarot del amor"
        - "tarot gratis"
        - "tarotista profesional"
      
      secundarias:
        - "tarot gitano"
        - "tarot egipcio"
        - "tarot rider"
        - "tarot marsella"
        - "oráculo de amor"
        - "lectura de futuro"
        - "videncia por chat"
        - "tarot telefónico"
        - "lectura rápida"
        - "tarot sin mentiras"
      
      long_tail:
        - "lectura de tarot profesional y certera"
        - "tarot en línea con vidente experta"
        - "consulta de tarot del amor gratis"
        - "tarot certero para conocer tu futuro"
        - "videncia online con tarot egipcio"
        - "lectura de cartas profesional inmediata"
        - "tarot del amor y relaciones verdadero"
        - "tarotista profesional con años de experiencia"
        - "lectura de tarot rápida y efectiva"
        - "videncia por chat disponible 24h"
    
    tonos_recomendados:
      - "místico"
      - "profesional"
      - "tranquilizador"
      - "informativo"
      - "espiritual"
    
    ctas_sugeridos:
      - "Consulta Tu Tarot Ahora"
      - "Lectura Gratis Disponible"
      - "Conoce Tu Futuro Ya"
      - "Vidente Experta Online"
      - "Respuestas Inmediatas"
      - "Tarot Certero Garantizado"
      - "Primera Consulta Gratis"
      - "Lectura Profesional Ya"
      - "Descubre Tu Destino"
      - "Tarotista Disponible 24h"
    
    descripciones_base:
      - "Lecturas de tarot profesionales y certeras. Vidente experta con años de experiencia. Primera consulta gratis."
      - "Tarot del amor, trabajo y dinero. Respuestas claras y honestas. Disponible online 24/7."
      - "Consulta de tarot con vidente profesional. Conoce tu futuro y toma mejores decisiones. Lecturas precisas."
      - "Tarot gitano, egipcio y rider. Lectura profunda de tu situación. Atención personalizada garantizada."
    
    url_patterns:
      - "/tarot"
      - "/lectura-de-tarot"
      - "/videncia"
      - "/consulta-tarot"
      - "/tarot-online"

# ============================================================================
# VARIACIONES DINÁMICAS
# ============================================================================
dynamic_variations:
  urgency_modifiers:
    - "Hoy"
    - "Ahora"
    - "Inmediato"
    - "24 Horas"
    - "Rápido"
    - "Urgente"
    - "Ya"
    - "En Minutos"
  
  quality_modifiers:
    - "Profesional"
    - "Experto"
    - "Certificado"
    - "Garantizado"
    - "Efectivo"
    - "Poderoso"
    - "Real"
    - "Auténtico"
  
  benefit_modifiers:
    - "Resultados Garantizados"
    - "Consulta Gratis"
    - "Sin Compromiso"
    - "Discreto"
    - "Confidencial"
    - "Personalizado"
    - "A Distancia"
    - "24/7 Disponible"

# ============================================================================
# REGLAS DE VALIDACIÓN
# ============================================================================
validation_rules:
  headlines:
    max_length: 30
    min_length: 10
    forbidden_words:
      - "gratis siempre"
      - "100% garantizado"
      - "milagro"
      - "infalible"
    required_elements:
      - "Debe contener una acción o beneficio"
  
  descriptions:
    max_length: 90
    min_length: 30
    forbidden_words:
      - "engaño"
      - "estafa"
      - "magia negra gratuita"
    required_elements:
      - "Debe incluir CTA o beneficio claro"

# ============================================================================
# CONFIGURACIÓN DE EXPORTACIÓN
# ============================================================================
export_settings:
  csv_format:
    delimiter: ","
    encoding: "utf-8"
    include_headers: true
    columns:
      - "Campaign"
      - "Ad Group"
      - "Headline 1"
      - "Headline 2"
      - "Headline 3"
      - "Description 1"
      - "Description 2"
      - "Final URL"
      - "Path 1"
      - "Path 2"
  
  json_format:
    pretty_print: true
    include_metadata: true
    include_validation: true